openapi: 3.0.0

info:
  version: 1.0.1
  title: "Code generation"

security:
  - bearerAuth: []
paths:
  /accounts:
    get:
      tags:
        - Accounts
      description: Returns a list of accounts
      parameters:
        - $ref: '#/components/parameters/PageLimit'
        - $ref: '#/components/parameters/PageOffset'
      responses:
        '200':
          description: Successfully returned a list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /users:
    get:
      tags:
        - Users
      description: Returns a list of users
      parameters:
        - $ref: '#/components/parameters/PageLimit'
        - $ref: '#/components/parameters/PageOffset'
      responses:
        '200':
          description: Successfully returned a list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /transactions:
    get:
      tags:
        - Transactions
      description: Returns a list of transactions
      parameters:
        - $ref: '#/components/parameters/PageLimit'
        - $ref: '#/components/parameters/PageOffset'
      responses:
        '200':
          description: Successfully returned a list of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /roles:
    get:
      tags:
        - Roles
      description: Returns a list of roles
      parameters:
        - $ref: '#/components/parameters/PageLimit'
        - $ref: '#/components/parameters/PageOffset'
      responses:
        '200':
          description: Successfully returned a list of roles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        user_id:
          type: integer
        iban:
          type: string
        limit:
          type: integer

    User:
      type: object
      properties:
        id:
          type: integer
        role_id:
          type: integer
        name:
          type: string
        email:
          type: string
        password:
          type: string

    Transaction:
      type: object
      properties:
        id:
          type: integer
        account_from_id:
          type: integer
        account_to_id:
          type: integer
        user_id:
          type: integer
        date:
          type: object
        amount:
          type: integer

    Role:
      type: object
      properties:
        id:
          type: integer
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'

    Permission:
      type: object
      properties:
        id:
          type: integer
        permission:
          type: string


  parameters:
    PageLimit:
      name: limit
      in: query
      description: Limits the number of items on a page
      schema:
        type: integer
    PageOffset:
      name: offset
      in: query
      description: Specifies the page number of the artists to be displayed
      schema:
        type: integer
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid